FROM elasticsearch:8.5.1

ENV IK_RELEASE=https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.5.1/elasticsearch-analysis-ik-8.5.1.zip
ENV STC_RELEASE=https://github.com/medcl/elasticsearch-analysis-stconvert/releases/download/v8.5.1/elasticsearch-analysis-stconvert-8.5.1.zip
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch $IK_RELEASE
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch $STC_RELEASE
