FROM elasticsearch:8.5.1

ENV IK_RELEASE=https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-8.5.1.zip
ENV STC_RELEASE=https://release.infinilabs.com/analysis-stconvert/stable/elasticsearch-analysis-stconvert-8.5.1.zip
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch $IK_RELEASE
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch $STC_RELEASE
